POST {{host}}/catalogues
Content-Type: application/json

{
    "Name": "Catalogue 1",
    "Items": []
}

> {%
    client.global.set("id", response.body.id);
  %}

###
GET {{host}}/catalogues

###
GET {{host}}/catalogues/{{id}}

###

PUT {{host}}/catalogues/{{id}}
Content-Type: application/json

{
  "Id": {{id}},
  "Name": "Catalogue 2",
  "Items": []
}

###
DELETE {{host}}/api/catalogues/{{id}}


