DB_CONTEXT=LibraryManagerDbContext
RELATIVE_FOLDER_PATH=Controllers

add_controller:
	dotnet aspnet-codegenerator controller -name $(MODEL)sController -m $(MODEL) -dc $(DB_CONTEXT) --relativeFolderPath $(RELATIVE_FOLDER_PATH) -actions -api
