// <auto-generated />
using System;
using LibraryManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryManager.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryManagerDbContext))]
    [Migration("20201129152955_update_non_nullable_props")]
    partial class update_non_nullable_props
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LibraryManager.Core.BibliographicRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BibliographicRecords");
                });

            modelBuilder.Entity("LibraryManager.Core.Catalogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catalogues");
                });

            modelBuilder.Entity("LibraryManager.Core.CatalogueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BibliographicRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CatalogueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BibliographicRecordId");

                    b.HasIndex("CatalogueId");

                    b.ToTable("CatalogueItems");
                });

            modelBuilder.Entity("LibraryManager.Core.CatalogueItem", b =>
                {
                    b.HasOne("LibraryManager.Core.BibliographicRecord", "BibliographicRecord")
                        .WithMany()
                        .HasForeignKey("BibliographicRecordId");

                    b.HasOne("LibraryManager.Core.Catalogue", null)
                        .WithMany("Items")
                        .HasForeignKey("CatalogueId");

                    b.Navigation("BibliographicRecord");
                });

            modelBuilder.Entity("LibraryManager.Core.Catalogue", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
